# Generated by Django 4.2.5 on 2023-10-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='djaba_id',
        ),
    ]
